//////////////////////////////////////////////////////////
// Coast Way Bridge Quest Cut Scene                     //
// The futile attempt to clear the bridge of explosives //
//////////////////////////////////////////////////////////

// There are 2 FF in the front
// PC goes behind them at 2818.1484
// If PC is posing as prisoner, there'll be another FF in the back
// A large contingent representing the whole of the FF will be lined up behind them
// The rest of the group, if any, will hang back until the fight begins


// Corwin will show up after the PC gets there
// And offer to join the group once more

// If there was an attempt to get the password, 
// a mage will show up before they leave to inform the fist
// The guard that provided the password will break the charm and alert the rest of the crusader guards

// If no attempt to get the password
// The two front fist will fail in their bluff

